[package]
name = "bonk-box"
version = "0.2.3"
description = "A stickman doodle on a sketchbook page."
authors = ["Granular"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-global-shortcut = "2"

[profile.release]
opt-level = "s"
lto = true
strip = true
